"""Wikipedia full-article lookup tool — direct MediaWiki API call via `requests`.

Why not the `wikipedia-api` library?
    `wikipedia-api>=0.7` uses `httpx` under the hood and constructs its
    `httpx.Client` in a way that swallows proxy env vars on Windows
    (likely `trust_env=False` on the inner client). Behind a corporate
    proxy this means every call fails with `getaddrinfo failed`, even
    though `httpx.get(...)` directly would work.

    `requests` on Windows reads the registry-level system proxy *and*
    `HTTP(S)_PROXY` env vars by default, so it works in:
      - Corporate-network laptops (proxy auto-detected)
      - SAP BAS (env vars OK)
      - Cloud Foundry (no proxy, direct egress)

The MediaWiki API itself is trivial enough to wrap ourselves; doing so
also avoids the third-party library.

Wikimedia's User-Agent policy
(https://meta.wikimedia.org/wiki/User-Agent_policy) requires the UA
to identify the application and provide a contact.

Why `action=parse` and NOT `action=query&prop=extracts`?
--------------------------------------------------------
The TextExtracts extension behind `prop=extracts` is designed for
"snippets / search previews", and on its own caps the returned prose
to a relatively short body — typically ~5–10 KB even for long
articles, with infoboxes, tables, references, footnote markers and
"see also" sections all stripped. Setting our own `_SUMMARY_CHAR_CAP`
higher than that buys nothing because the API itself never returns
more.

`action=parse&prop=text` instead returns the **fully rendered HTML
of the entire article**, which we strip down ourselves. This gives
us all the section bodies (生平 / 早年生活 / 求学 / 二战时期 / 战后 /
死亡 / 政府道歉 / 认可 / …), capped only by `_SUMMARY_CHAR_CAP`.

Multilingual support
--------------------
Every Wikipedia language edition exposes the same MediaWiki API at
`https://<lang>.wikipedia.org/w/api.php` — only the subdomain changes.
The tool exposes `lang` as a parameter so the LLM can route based on
the question's language (e.g. "图灵简介" → lang="zh").
"""

from __future__ import annotations

import html as _html
import json
import re
import sys
from typing import Any
from urllib.parse import quote

import requests
from langchain_core.tools import tool


_USER_AGENT = (
    "ChatOpenAI-AgentTools-Demo/1.0 "
    "(https://github.com/UUS1SGH/ChatOpenAI_AgentTools; demo)"
)
_TIMEOUT_S = 15

# Cap on the cleaned plain-text body returned to the LLM.
# Note: this directly drives token cost (Chinese: ~1 token/char,
# English: ~0.25 token/char), so don't crank it too high if you care
# about cost. 8000–12000 is a good range for "near-complete article";
# 80000 is essentially "give me everything".
_SUMMARY_CHAR_CAP = 80000

# A small allow-list keeps the LLM from inventing exotic codes
# (e.g. "english", "chinese") that don't exist as Wikipedia subdomains.
# Add more as needed — every entry must be a valid Wikipedia subdomain.
_SUPPORTED_LANGS: set[str] = {"en", "zh", "de", "fr", "ja", "ko", "es", "ru"}
_DEFAULT_LANG = "en"


# ============================================================
# HTML → plain-text cleaner
# ============================================================
#
# The MediaWiki `action=parse&prop=text` endpoint returns the article's
# rendered HTML. We strip noisy / non-prose elements with regex. This is
# deliberately not a full HTML parser — Wikipedia's HTML is generated by
# Parsoid / mediawiki-core and is reasonably consistent, so simple regex
# is enough for our purposes (and avoids depending on bs4 / lxml).

# Tags whose ENTIRE element + content must be discarded. Without this,
# our naive `<...>`-stripping would keep the literal CSS / JS text that
# lives inside <style> / <script>.
_DROP_WHOLE_TAG_RE = re.compile(
    r"<(style|script)\b[^>]*>.*?</\1>",
    flags=re.DOTALL | re.IGNORECASE,
)

# Block-level elements we want to drop entirely (the WHOLE element + its
# inner content). Each pattern is `(open_tag_regex, kind)`. Kind is
# "table" or "div" / "span" — we use it only to know the closing tag.
_BLOCK_DROP_PATTERNS: list[tuple[str, str]] = [
    # Infoboxes, navboxes, sidebars, metadata, and quote/citation tables
    (r'<table\b[^>]*\bclass="[^"]*\b(?:infobox|navbox|metadata|sidebar|vertical-navbox|wikitable|sister-bar)\b[^"]*"[^>]*>', "table"),
    # Reference lists, sister-site boxes, portal bars (those are "after-content" widgets)
    (r'<div\b[^>]*\bclass="[^"]*\b(?:reflist|references|navbox|sister-bar|sistersitebox|portal-bar|portalbox|navigation-only)\b[^"]*"[^>]*>', "div"),
    # Hatnotes (top-of-section "see also: X" links)
    (r'<div\b[^>]*\bclass="[^"]*\b(?:hatnote|dablink)\b[^"]*"[^>]*>', "div"),
    # ToC widget
    (r'<div\b[^>]*\bid="toc"[^>]*>', "div"),
    # Edit-section widget
    (r'<span\b[^>]*\bclass="[^"]*\bmw-editsection\b[^"]*"[^>]*>', "span"),
    # Inline reference markers <sup class="reference">[1]</sup>
    (r'<sup\b[^>]*\bclass="[^"]*\breference\b[^"]*"[^>]*>', "sup"),
    # Coordinates widget
    (r'<span\b[^>]*\bid="coordinates"[^>]*>', "span"),
]

_HEADING_RE = re.compile(r"<h([1-6])\b[^>]*>(.*?)</h\1>", flags=re.DOTALL | re.IGNORECASE)
_PARA_RE = re.compile(r"</(?:p|li|tr|h[1-6]|div|section|blockquote)>", flags=re.IGNORECASE)
_TAG_RE = re.compile(r"<[^>]+>")
_MULTI_BLANK_RE = re.compile(r"\n{3,}")

# Section titles that mark the boundary between "real content" and
# bibliography / further-reading / external-links / portal navigation.
# Everything from the first hit onward is dropped. Multilingual to match
# the languages we support; comparison is case-insensitive.
_STOP_SECTION_TITLES_LOWER: set[str] = {
    # English
    "see also", "references", "notes", "external links", "further reading",
    "citations", "sources", "bibliography", "footnotes", "works cited",
    # Chinese (simplified + traditional)
    "参见", "參見", "另见", "另見", "另请参阅", "另請參閱",
    "参考", "參考", "注释", "註釋", "脚注", "腳註",
    "参考资料", "參考資料", "参考文献", "參考文獻",
    "外部链接", "外部鏈接", "外部連結",
    "延伸阅读", "延伸閱讀", "扩展阅读", "擴展閱讀",
    "参考来源", "參考來源", "引用",
    # German
    "siehe auch", "einzelnachweise", "literatur", "weblinks",
    "anmerkungen", "quellen", "fußnoten",
    # French
    "voir aussi", "notes et références", "bibliographie",
    "liens externes", "références", "annexes",
    # Japanese
    "出典", "参考文献", "関連項目", "外部リンク", "脚注の使い方",
    # Korean
    "참고 문헌", "각주", "외부 링크", "함께 보기", "주석",
    # Spanish
    "véase también", "referencias", "notas", "bibliografía",
    "enlaces externos", "obras citadas",
    # Russian
    "см. также", "примечания", "литература", "ссылки", "источники",
}


def _truncate_at_stop_section(text: str) -> str:
    """Drop everything from the first 'See also'-style section onward.

    Wikipedia articles end with a fairly stereotyped tail: 参见 / References /
    External links / Bibliography / portal bars / sister-site boxes. None of
    that is useful prose for an LLM, so we cut it off at the first matching
    heading. The set covers all language editions we support.
    """
    if not text:
        return text
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip().lower() in _STOP_SECTION_TITLES_LOWER:
            return "\n".join(lines[:i]).rstrip()
    return text


def _strip_block(html: str, open_pattern: str, kind: str) -> str:
    """Remove every <kind>…</kind> whose opening tag matches `open_pattern`.

    Handles simple nesting by counting opens/closes for the given tag kind.
    Good enough for Wikipedia's well-formed HTML.
    """
    open_re = re.compile(open_pattern, flags=re.IGNORECASE | re.DOTALL)
    close_tag = f"</{kind}>"
    open_tag_short = f"<{kind}"

    out: list[str] = []
    pos = 0
    for m in open_re.finditer(html):
        out.append(html[pos:m.start()])
        # Walk forward, balancing nested same-kind tags
        depth = 1
        i = m.end()
        while i < len(html) and depth > 0:
            next_open = html.find(open_tag_short, i)
            next_close = html.find(close_tag, i)
            if next_close == -1:
                # Malformed — cut to end.
                i = len(html)
                break
            if next_open != -1 and next_open < next_close:
                depth += 1
                i = next_open + len(open_tag_short)
            else:
                depth -= 1
                i = next_close + len(close_tag)
        pos = i
    out.append(html[pos:])
    return "".join(out)


def _html_to_plain(html: str) -> str:
    """Convert MediaWiki rendered HTML into clean plain text."""
    # 0. Drop <style> and <script> elements *with* their content (otherwise
    #    the literal CSS / JS body would survive a naïve tag strip).
    html = _DROP_WHOLE_TAG_RE.sub("", html)

    # 1. Drop unwanted block-level elements + their content
    for pattern, kind in _BLOCK_DROP_PATTERNS:
        html = _strip_block(html, pattern, kind)

    # 2. Promote headings to "\n\nHeading\n\n" so the structure survives
    html = _HEADING_RE.sub(lambda m: f"\n\n{m.group(2).strip()}\n\n", html)

    # 3. Insert paragraph breaks at the end of block-level elements.
    html = _PARA_RE.sub("\n\n", html)

    # 4. Strip remaining HTML tags
    text = _TAG_RE.sub("", html)

    # 5. Decode HTML entities (&nbsp; &amp; &#39; …)
    text = _html.unescape(text)

    # 6. Strip per-line whitespace, drop empty lines runs
    lines = [line.rstrip() for line in text.splitlines()]
    text = "\n".join(lines).strip()
    text = _MULTI_BLANK_RE.sub("\n\n", text)

    # 7. Cut off the bibliography / external-links / portal-bar tail.
    text = _truncate_at_stop_section(text)

    return text


# ============================================================
# Tool
# ============================================================


@tool
def search_wikipedia(query: str, lang: str = _DEFAULT_LANG) -> str:
    """Look up a topic on Wikipedia and return the article's full plain-text body.

    Use this for general factual / encyclopedic knowledge: people,
    places, historical events, scientific concepts, organisations, and
    other well-known entities. The tool returns the entire article body
    in plain text (capped to `_SUMMARY_CHAR_CAP` characters), with
    section headings preserved.

    Do NOT use this for:
      - Live news, current events, or anything time-sensitive (use
        `tavily_search` instead).
      - Internal product / company documentation (use
        `knowledge_base_search` instead).
      - Definitions of common dictionary words.

    Args:
        query: Topic or article title to look up. Should be in the same
            language as `lang` for best results. Don't include extra
            words like "what is" — just the bare topic.
        lang: Wikipedia language edition to query. Pick based on the
            user's question language:
              - "en" (default) → English Wikipedia (most articles)
              - "zh"           → Chinese Wikipedia (中文维基)
              - "de" / "fr" / "ja" / "ko" / "es" / "ru" → other major editions
            If the topic isn't found in the chosen edition you may retry
            with a different `lang` (e.g. fall back to "en" for niche
            international topics).

    Returns:
        JSON string of the form
            `{"title": "<page title>", "summary": "<full article text>",
              "url": "<wikipedia url>", "lang": "<lang>"}`,
        or `{"error": "<message>"}` if the page cannot be found.
    """
    lang = (lang or _DEFAULT_LANG).strip().lower()
    if lang not in _SUPPORTED_LANGS:
        return json.dumps(
            {
                "error": (
                    f"Unsupported lang '{lang}'. Choose one of: "
                    f"{sorted(_SUPPORTED_LANGS)}"
                )
            }
        )

    api_url = f"https://{lang}.wikipedia.org/w/api.php"

    try:
        # MediaWiki parse API:
        #   prop=text          → rendered HTML of the article body
        #   prop=displaytitle  → the canonical title (with proper Han variant for zh)
        #   redirects=1        → follow redirects automatically
        #   disabletoc=1       → drop the table-of-contents widget
        #   disableeditsection=1 → drop the "[edit]" links from each heading
        #   formatversion=2    → cleaner JSON shape (no `*` magic key)
        response = requests.get(
            api_url,
            params={
                "action": "parse",
                "page": query,
                "prop": "text|displaytitle",
                "redirects": 1,
                "disabletoc": 1,
                "disableeditsection": 1,
                "format": "json",
                "formatversion": 2,
            },
            headers={"User-Agent": _USER_AGENT},
            timeout=_TIMEOUT_S,
        )
        response.raise_for_status()
        data: dict[str, Any] = response.json()

        if "error" in data:
            err_info = data["error"]
            code = err_info.get("code", "unknown")
            info = err_info.get("info", "")
            if code in {"missingtitle", "nosuchpageid"}:
                return json.dumps(
                    {"error": f"No Wikipedia page found for '{query}' (lang={lang})"}
                )
            return json.dumps(
                {"error": f"Wikipedia API error ({code}) for '{query}': {info}"}
            )

        parse_block = data.get("parse") or {}
        title = parse_block.get("title") or query
        # `text` is a string under formatversion=2 (vs. {"*": "..."} in v1)
        raw_html = parse_block.get("text") or ""
        if isinstance(raw_html, dict):
            raw_html = raw_html.get("*", "")
        if not raw_html:
            return json.dumps(
                {"error": f"Wikipedia page '{title}' has empty content"}
            )

        plain = _html_to_plain(raw_html)
        if not plain:
            return json.dumps(
                {"error": f"Wikipedia page '{title}' produced empty plain text"}
            )

        if len(plain) > _SUMMARY_CHAR_CAP:
            plain = plain[:_SUMMARY_CHAR_CAP].rstrip() + "…"

        url = f"https://{lang}.wikipedia.org/wiki/{quote(title.replace(' ', '_'))}"

        return json.dumps(
            {"title": title, "summary": plain, "url": url, "lang": lang}
        )

    except Exception as e:  # noqa: BLE001 — surface any failure to the agent
        err_msg = (
            f"Wikipedia lookup failed for '{query}' (lang={lang}): "
            f"{type(e).__name__}: {e}"
        )
        print(f"[tools.wikipedia] {err_msg}", file=sys.stderr, flush=True)
        return json.dumps({"error": err_msg})
